# app.py
"""
Streamlit UI for real vs synthetic dataset inspection

How to run:
1) create an env with the requirements below and activate it
2) streamlit run app.py

Features:
- upload dataset (CSV/TSV/JSONL)
- auto-detect text column (or pick manually)
- quick cleaning & leak inspection
- optional: upload a scikit-learn pickle classifier (expects .predict or .predict_proba on raw text) OR specify a HF model dir to use (AutoModelForSequenceClassification)
- fallback heuristic detector when no model provided
- shows pie chart, bar, top suspicious rows, and allows download of labeled CSV
"""

import io, os, re, json
from typing import Optional, List, Dict, Any
import streamlit as st
import pandas as pd
import numpy as np
from collections import Counter

# Optional imports (we'll try to lazy-import heavy libs)
_SKLEARN_AVAILABLE = False
_TRANSFORMERS_AVAILABLE = False
_TORCH_AVAILABLE = False
_SENTENCE_TRANSFORMERS = False

try:
    import joblib
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.linear_model import LogisticRegression
    _SKLEARN_AVAILABLE = True
except Exception:
    _SKLEARN_AVAILABLE = False

try:
    import torch
    from transformers import AutoTokenizer, AutoModelForSequenceClassification
    _TRANSFORMERS_AVAILABLE = True
    _TORCH_AVAILABLE = True
except Exception:
    _TRANSFORMERS_AVAILABLE = False
    _TORCH_AVAILABLE = False

# -------- Helpers --------
def read_dataset(uploaded_file: io.BytesIO, filename: str) -> pd.DataFrame:
    name = filename.lower()
    uploaded_file.seek(0)
    if name.endswith(".csv"):
        return pd.read_csv(uploaded_file, dtype=str, encoding='utf-8', low_memory=False)
    if name.endswith(".tsv") or name.endswith(".txt"):
        return pd.read_csv(uploaded_file, sep="\t", dtype=str, encoding='utf-8', low_memory=False)
    if name.endswith(".json") or name.endswith(".jsonl"):
        return pd.read_json(uploaded_file, lines=True)
    # fallback: try csv
    try:
        return pd.read_csv(uploaded_file, dtype=str, encoding='utf-8', low_memory=False)
    except Exception:
        uploaded_file.seek(0)
        text = uploaded_file.read().decode('utf-8', errors='ignore')
        return pd.DataFrame({"text": [text]})

def simple_clean(s: str) -> str:
    if s is None:
        return ""
    s = str(s)
    s = re.sub(r"<[^>]+>", " ", s)  # strip HTML tags
    s = re.sub(r"https?://\S+|www\.\S+|\S+@\S+", " ", s)  # strip urls/emails
    s = re.sub(r"\s+", " ", s).strip()
    return s

def detect_text_column(df: pd.DataFrame) -> List[str]:
    # prefer 'text' columns, otherwise long string columns
    candidates = []
    lower = [c.lower() for c in df.columns]
    if 'text' in lower:
        idx = lower.index('text')
        candidates.append(df.columns[idx])
    # add columns with many long strings
    lengths = {c: df[c].astype(str).map(len).median() for c in df.columns}
    # sort by median length desc
    sorted_cols = sorted(lengths.items(), key=lambda kv: kv[1], reverse=True)
    for c, _ in sorted_cols[:3]:
        if c not in candidates:
            candidates.append(c)
    return candidates

def keyword_leak_score(text: str, keywords: List[str]) -> int:
    t = text.lower()
    for k in keywords:
        if k in t:
            return 1
    return 0

def repetition_ratio(text: str) -> float:
    toks = text.split()
    if not toks:
        return 0.0
    c = Counter(toks)
    most_common = c.most_common(1)[0][1]
    return most_common / max(1, len(toks))

def heuristic_synthetic_score(series: pd.Series) -> np.ndarray:
    """
    For each text produce a score 0..1 indicating likelihood synthetic based on heuristic rules:
    - presence of "generated" tokens, model names, or html artifacts (strong signal)
    - presence of urls/html/email (weak signal)
    - extremely short or extremely long (weak signal)
    - repetition ratio high (weak signal)
    Weighted sum normalized to [0,1].
    """
    keywords = ["generated by", "generated", "gpt", "llama", "openai", "davinci", "chatgpt", "gpt-3", "gpt-4",
                "synth", "__synth__", "synthetic", "ai generated", "generated_text", "generator"]
    kw_arr = series.fillna("").astype(str).map(lambda s: keyword_leak_score(s, keywords)).to_numpy(dtype=float)
    html_arr = series.fillna("").astype(str).map(lambda s: 1.0 if re.search(r"<\/?\w+>", s) else 0.0).to_numpy()
    url_arr = series.fillna("").astype(str).map(lambda s: 1.0 if re.search(r"https?://|www\.", s) else 0.0).to_numpy()
    rep_arr = series.fillna("").astype(str).map(repetition_ratio).to_numpy()
    lens = series.fillna("").astype(str).map(len).to_numpy(dtype=float)
    # length score: very short (<20) or very long (>2000) may be synthetic or truncated - use logistic-ish scoring
    len_score = np.clip((lens - 20) / (200 - 20), 0, 1)
    len_score = 1 - np.abs(len_score - 0.5) * 2  # peak in middle -> lower score, extremes higher
    # combine
    # weights tuned for quick feedback; later replace with ML model
    score = (kw_arr * 0.5) + (html_arr * 0.15) + (url_arr * 0.05) + (rep_arr * 0.15) + (len_score * 0.15)
    # normalize to [0,1]
    score = np.clip(score, 0.0, 1.0)
    return score

def load_sklearn_model(uploaded_bytes: io.BytesIO):
    # expects a joblib or pickle containing an object with .predict or .predict_proba that accepts list[str]
    try:
        uploaded_bytes.seek(0)
        model = joblib.load(uploaded_bytes)
        return model
    except Exception as e:
        st.error(f"Failed to load sklearn model: {e}")
        return None

def predict_with_sklearn(model, texts: List[str]) -> np.ndarray:
    # Try predict_proba otherwise predict
    try:
        if hasattr(model, "predict_proba"):
            probs = model.predict_proba(texts)
            # handle 2d -> class1 probability
            if probs.ndim == 2 and probs.shape[1] >= 2:
                return probs[:, 1]
            # fallback: use max column
            return np.max(probs, axis=1)
        else:
            preds = model.predict(texts)
            return np.array(preds, dtype=float)
    except Exception as e:
        st.warning(f"sklearn model prediction failed: {e}")
        return np.zeros(len(texts), dtype=float)

def load_hf_model_from_dir(model_dir: str):
    # loads HF model and tokenizer from a directory path
    if not _TRANSFORMERS_AVAILABLE:
        st.error("transformers/torch not available in this environment.")
        return None, None
    try:
        tokenizer = AutoTokenizer.from_pretrained(model_dir, use_fast=True)
        model = AutoModelForSequenceClassification.from_pretrained(model_dir)
        return tokenizer, model
    except Exception as e:
        st.error(f"Failed to load HF model from {model_dir}: {e}")
        return None, None

def predict_with_hf(tokenizer, model, texts: List[str], device: Optional[str]=None) -> np.ndarray:
    import torch.nn.functional as F
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"
    model.to(device)
    model.eval()
    all_probs = []
    batch_size = 16
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]
        enc = tokenizer(batch, truncation=True, padding=True, return_tensors="pt")
        enc = {k: v.to(device) for k, v in enc.items()}
        with torch.no_grad():
            out = model(**enc)
            logits = out.logits
            probs = F.softmax(logits, dim=1)[:, 1].cpu().numpy()
            all_probs.extend(probs.tolist())
    return np.array(all_probs, dtype=float)

# -------- Streamlit UI --------
st.set_page_config(page_title="Real vs Synthetic Inspector", layout="wide")
st.title("📊 Real vs Synthetic — Dataset Inspector")

col1, col2 = st.columns([2,1])

with col1:
    st.header("1) Upload dataset")
    uploaded = st.file_uploader("Choose CSV/TSV/JSONL file", type=["csv","tsv","txt","json","jsonl"])
    st.markdown("Or pick an existing file path on disk (local path).")
    local_path = st.text_input("Local file path (optional, overrides upload)", value="")
    use_local = False
    df = None
    if local_path.strip():
        if os.path.exists(local_path):
            use_local = True
            try:
                df = read_dataset(open(local_path, "rb"), local_path)
                st.success(f"Loaded local file: {local_path} ({len(df)} rows)")
            except Exception as e:
                st.error(f"Failed to load local file: {e}")
        else:
            st.info("Local path does not exist yet.")
    if uploaded is not None and not use_local:
        try:
            df = read_dataset(uploaded, uploaded.name)
            st.success(f"Loaded uploaded file: {uploaded.name} ({len(df)} rows)")
        except Exception as e:
            st.error(f"Failed to read uploaded file: {e}")
    if df is None:
        st.info("Please upload a dataset or specify a local file path to get started.")
    else:
        st.write("Columns:", list(df.columns))
        # detect candidate text columns
        candidates = detect_text_column(df)
        st.subheader("2) Choose text column")
        chosen = st.selectbox("Detected candidate text columns (pick the one with main full text)", candidates, index=0)
        label_col_default = None
        if 'label' in [c.lower() for c in df.columns]:
            # pick 'label' if exists
            for c in df.columns:
                if c.lower() == 'label':
                    label_col_default = c
        st.subheader("3) (Optional) Label column (if your dataset already has ground truth)")
        label_col = st.selectbox("Label column (optional)", options=["(none)"] + list(df.columns), index=0 if label_col_default is None else list(df.columns).index(label_col_default)+1)
        st.markdown("---")
        st.subheader("4) Cleaning & dedup options")
        dedup_exact = st.checkbox("Drop exact duplicate text rows", value=True)
        dedup_near = st.checkbox("Do near-duplicate removal (slow for large sets)", value=False)
        dedup_near_thresh = 0.92
        if dedup_near:
            dedup_near_thresh = st.slider("Near-duplicate similarity threshold", min_value=0.8, max_value=0.99, value=0.92, step=0.01)
        st.markdown("---")
        st.subheader("5) Model / Detector options")
        st.write("You can provide a trained model (preferred) or use the heuristic fallback.")
        sk_model_file = st.file_uploader("Upload sklearn joblib/pickle model (.joblib/.pkl) (optional)", type=["joblib","pkl"], key="sk")
        hf_model_dir = st.text_input("Or path to HF model directory (optional)", value="")
        use_hf = False
        sk_model = None
        hf_tokenizer = hf_model = None
        if sk_model_file is not None:
            if _SKLEARN_AVAILABLE:
                sk_model = load_sklearn_model(sk_model_file)
                if sk_model:
                    st.success("Loaded sklearn model (will use for predictions).")
            else:
                st.warning("sklearn not available in this environment; model cannot be loaded.")

        if hf_model_dir.strip():
            if os.path.exists(hf_model_dir):
                if _TRANSFORMERS_AVAILABLE:
                    hf_tokenizer, hf_model = load_hf_model_from_dir(hf_model_dir)
                    if hf_model is not None:
                        st.success("Loaded HF model directory (will use for predictions).")
                        use_hf = True
                else:
                    st.warning("transformers/torch not available; cannot load HF model here.")
            else:
                st.warning("HF model dir path does not exist.")

        st.markdown("---")
        st.subheader("6) Run detection")
        run_btn = st.button("Run analysis")

with col2:
    st.markdown("### Quick notes")
    st.markdown("""
    - The app uses a **heuristic fallback** when you don't provide a model.
    - Best accuracy: upload a trained classifier (sklearn/pickle that supports `predict_proba` over raw text) or a HuggingFace model directory.
    - After running you'll get: pie chart (% real vs synth), sample suspicious rows, and a downloadable CSV of predictions.
    - The heuristic detector is conservative and intended for quick inspection; it's not a substitute for training a proper classifier.
    """)
    st.markdown("---")
    st.markdown("### Environment status")
    st.write(f"sklearn available: {_SKLEARN_AVAILABLE}")
    st.write(f"transformers available: {_TRANSFORMERS_AVAILABLE}")
    st.write(f"torch available: {_TORCH_AVAILABLE}")

# -------- Run analysis when asked -------
if 'run_btn' in locals() and run_btn and df is not None:
    st.subheader("Results")
    # Prepare dataframe copy
    df_proc = df.copy()
    # ensure chosen col exists
    if chosen not in df_proc.columns:
        st.error("Chosen text column not found.")
    else:
        # cleaning
        st.info("Cleaning text...")
        df_proc['__text_raw'] = df_proc[chosen].astype(str)
        df_proc['__text'] = df_proc['__text_raw'].map(simple_clean)

        # dedupe exact
        if dedup_exact:
            before = len(df_proc)
            df_proc = df_proc.drop_duplicates(subset=['__text']).reset_index(drop=True)
            st.write(f"Dropped {before - len(df_proc)} exact duplicate rows.")

        # near dedupe (naive O(n^2))
        if dedup_near:
            st.info(f"Running near-dedup at threshold {dedup_near_thresh} (this can be slow)...")
            # naive; for thousands it's borderline; we warn
            texts = df_proc['__text'].tolist()
            keep_idx = []
            from difflib import SequenceMatcher
            for i, t in enumerate(texts):
                skip = False
                for j in keep_idx:
                    sim = SequenceMatcher(None, t, texts[j]).ratio()
                    if sim >= dedup_near_thresh:
                        skip = True
                        break
                if not skip:
                    keep_idx.append(i)
            df_proc = df_proc.iloc[keep_idx].reset_index(drop=True)
            st.write(f"After near-dedup: {len(df_proc)} rows")

        st.write("Dataset size for analysis:", len(df_proc))

        # run heuristic scoring
        st.info("Computing heuristic synthetic score...")
        scores = heuristic_synthetic_score(df_proc['__text'])
        df_proc['heuristic_score'] = scores

        # if sklearn model uploaded, use it
        use_model = False
        probs = None
        if sk_model is not None:
            st.info("Predicting with uploaded sklearn model...")
            try:
                texts = df_proc['__text'].astype(str).tolist()
                probs = predict_with_sklearn(sk_model, texts)
                # if predict returned integer labels, convert to 0/1 probabilities
                if probs.dtype.kind in 'iu':
                    probs = probs.astype(float)
                # normalize to 0..1 if necessary
                if probs.max() > 1.0 or probs.min() < 0.0:
                    probs = (probs - probs.min()) / max(1e-8, (probs.max() - probs.min()))
                df_proc['model_prob'] = probs
                use_model = True
                st.success("sklearn model predictions added.")
            except Exception as e:
                st.warning(f"sklearn prediction error: {e}")

        elif hf_model is not None and hf_tokenizer is not None:
            st.info("Predicting with provided HuggingFace model...")
            try:
                texts = df_proc['__text'].astype(str).tolist()
                probs = predict_with_hf(hf_tokenizer, hf_model, texts)
                df_proc['model_prob'] = probs
                use_model = True
                st.success("HF model predictions added.")
            except Exception as e:
                st.warning(f"HF model prediction error: {e}")

        # final probability - prefer model_prob if available else heuristic
        if 'model_prob' in df_proc.columns:
            df_proc['final_prob_synth'] = df_proc['model_prob']
            st.write("Using uploaded model for final probability.")
        else:
            # smooth combine heuristic with a pseudo-model from TF-IDF+logreg if sklearn exists and no model uploaded
            if _SKLEARN_AVAILABLE and (not use_model):
                st.info("Training a lightweight TF-IDF+LogReg internal model on-the-fly (unsupervised fallback uses heuristic labels) ...")
                # create weak labels from heuristic to bootstrap quick classifier
                weak_labels = (df_proc['heuristic_score'] > 0.5).astype(int)
                try:
                    vect = TfidfVectorizer(max_features=20000, ngram_range=(1,2))
                    X = vect.fit_transform(df_proc['__text'].astype(str).tolist())
                    clf = LogisticRegression(max_iter=500)
                    clf.fit(X, weak_labels)
                    probs = clf.predict_proba(X)[:,1]
                    df_proc['tfidf_prob'] = probs
                    # combine heuristic and tfidf weak model
                    df_proc['final_prob_synth'] = (df_proc['heuristic_score'] * 0.45) + (df_proc['tfidf_prob'] * 0.55)
                    st.success("Lightweight model trained and combined with heuristic.")
                except Exception as e:
                    st.warning(f"Lightweight model failed: {e}. Falling back to heuristic alone.")
                    df_proc['final_prob_synth'] = df_proc['heuristic_score']
            else:
                df_proc['final_prob_synth'] = df_proc['heuristic_score']
                st.write("Using heuristic score as final probability (no model provided).")

        # classify: threshold slider
        st.subheader("Classification threshold")
        thresh = st.slider("Probability threshold for 'synthetic' class", min_value=0.0, max_value=1.0, value=0.5, step=0.01)
        df_proc['pred_label'] = (df_proc['final_prob_synth'] >= thresh).astype(int)

        # Summary numbers
        total = len(df_proc)
        synth_count = int(df_proc['pred_label'].sum())
        real_count = total - synth_count
        synth_pct = synth_count / total * 100.0
        real_pct = real_count / total * 100.0

        st.metric("Total rows analyzed", total)
        st.metric("Estimated synthetic (%)", f"{synth_pct:.2f}%")
        st.metric("Estimated real (%)", f"{real_pct:.2f}%")

        # Charts
        st.subheader("Charts")
        chart_df = pd.DataFrame({
            "label": ["real", "synthetic"],
            "count": [real_count, synth_count]
        })
        st.bar_chart(data=chart_df.set_index("label"))
        st.write("Distribution pie (approx):")
        st.pyplot(
            __import__("matplotlib").pyplot.figure(figsize=(4,4))
            or None
        )  # placeholder to ensure matplotlib available below

        import matplotlib.pyplot as plt
        fig, ax = plt.subplots(figsize=(4,4))
        ax.pie([real_count, synth_count], labels=["real", "synthetic"], autopct="%1.1f%%", colors=None)
        ax.set_title("Estimated composition")
        st.pyplot(fig)

        # Top suspicious rows (highest final_prob)
        st.subheader("Top suspicious (highest synthetic probability)")
        topk = st.number_input("How many top suspicious rows to show", min_value=3, max_value=100, value=10, step=1)
        top = df_proc.sort_values("final_prob_synth", ascending=False).head(int(topk))
        # show a small table (raw + probability)
        display_cols = ['__text_raw', 'final_prob_synth', 'pred_label']
        for c in df_proc.columns:
            # keep original columns if user wants to see them
            if c not in display_cols and c in df.columns:
                display_cols.insert(0, c)
        st.dataframe(top[display_cols].rename(columns={'__text_raw': 'text'}), height=300)

        # Leakage report
        st.subheader("Leakage & token checks (quick)")
        leak_keywords = ["generated", "gpt", "openai", "llama", "generated_by", "synthetic", "__synth__", "source:"]
        leak_counts = {}
        for k in leak_keywords:
            leak_counts[k] = int(df_proc['__text'].astype(str).str.contains(k, case=False, na=False).sum())
        st.write("Counts for suspicious tokens/markers:")
        st.json(leak_counts)

        # If label column existed, show confusion-like quick check
        if label_col != "(none)":
            true_col = label_col
            # ensure numeric
            try:
                df_proc['_true_label'] = df_proc[true_col].astype(int)
                from sklearn.metrics import classification_report
                report = classification_report(df_proc['_true_label'], df_proc['pred_label'], output_dict=True)
                st.subheader("If ground-truth label provided — quick report")
                st.json(report)
            except Exception as e:
                st.info("Could not compute ground-truth comparison (label column not integer / incompatible).")

        # allow download
        st.subheader("Download annotated file")
        out_path = st.text_input("Output filename (download local browser copy)", value="results/predictions_inspected.csv")
        buf = df_proc.copy()
        # put final fields at end for readability
        if '__text' in buf.columns and '__text_raw' in buf.columns:
            pass
        # write CSV to buffer
        csv_bytes = buf.to_csv(index=False).encode('utf-8')
        st.download_button("Download CSV with predictions", data=csv_bytes, file_name=os.path.basename(out_path), mime="text/csv")
        st.success("Done. You can now inspect suspicious rows and download results.")
